CREATE TABLE USER (
    RECORD_ID BIGINT NOT NULL AUTO_INCREMENT,
    USERID VARCHAR(36) NOT NULL UNIQUE,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CREATED_BY VARCHAR(50),
    CREATED_DT DATETIME,
    LAST_MODIFY_BY VARCHAR(50),
    LAST_MODIFY_DT DATETIME,
    RECORD_VERSION BIGINT DEFAULT 0,
    PRIMARY KEY (RECORD_ID)
);


CREATE TABLE MESSAGE (
    RECORD_ID BIGINT NOT NULL AUTO_INCREMENT,
    MESSAGEID VARCHAR(36) NOT NULL,
    USERID VARCHAR(36) NOT NULL,
    CONTENT TEXT,
    SENDER VARCHAR(2) NOT NULL, # 'A' for AI, 'U' for user
    CREATED_BY VARCHAR(50),
    CREATED_DT DATETIME,
    LAST_MODIFY_BY VARCHAR(50),
    LAST_MODIFY_DT DATETIME,
    RECORD_VERSION BIGINT DEFAULT 0,
    PRIMARY KEY (RECORD_ID),
    FOREIGN KEY (USERID) REFERENCES USER(USERID)
);